server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  absolute_redirect off;

  location = / {
    return 302 /tours/__SLUG__/;
  }

  location /_next/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location /tours/__SLUG__/panoramas/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }

  location /tours/__SLUG__/markers/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ $uri.html =404;
  }
}
